### ISSUE TITLE
Severe case of shader issues (Only fraction of Vertices being rendering)

### ISSUE THREAD

**Issue by ghost** [GarrettGunnell/Water#2]
![Screenshot_20230904_205535](https://github.com/GarrettGunnell/Water/assets/12180913/67f08003-fd11-4e95-80e0-9c3b23b9d801)
![image](https://github.com/GarrettGunnell/Water/assets/12180913/15ed32b9-71ba-40d3-a6b0-a1a2f5769917)

**Comment by ghost** [comment]
![image](https://github.com/GarrettGunnell/Water/assets/12180913/d00ea9c8-77a6-4372-8232-31a0672d6e5e)
Note, issue seems to be less severe when using vulkan

**Comment by GarrettGunnell** [comment]
Yeah I use the dx11 backend. I don't know why this would be breaking on opengl or vulkan.

**Comment by hugo-blomdahl** [comment]
For reference if anyone in the future wants to run this on Linux.
You can build the demo for windows using the linux version of the unity editor. You can then run the resulting build using wine/dxvk. Easiest is to add the demo exe to steam and run it using proton.
