### ISSUE TITLE
buoy2 (3) (Missing Prefab with guid: ba836e03ed0a85d4889533b6dc1e27e3)

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [GarrettGunnell/Water#3]
![image](https://github.com/GarrettGunnell/Water/assets/6131040/4c1ca993-2dc2-4c4c-9d76-a5d1872e3216)

**Comment by GarrettGunnell** [comment]
yeah you can just put your own model in lol I dont really intend for the scene to be used I should put it in the gitignore my bad
